### ISSUE TITLE
Issue with the loop

### ISSUE THREAD

**Issue by amalsebastian7** [PhoenixCreation/whatsapp-spammer#1] opened 2022-08-25 10:51 UTC
```
var count = prompt("Enter number of messages");
var message = prompt("MESSAGE YOU WANT TO SPAM : ", "Hello ");
console.clear();
for (let i = 0; i < count; i++) {
    console.log(`"${message}" sent -> ${i + 1} times`);

      // Get the input box
      var box = document.querySelectorAll("[role=textbox]")[1];

      // create event of type 'input' so that the whatsapp UI will update to sending text message instead of voice message
      InputEvent = Event || InputEvent;
      var evt = new InputEvent("input", {
        bubbles: true,
        composer: true,
      });
      box.innerHTML = message; // set the message as input box value
      box.dispatchEvent(evt); // trigger the event

      // This is bit of stratch to select the send button and click it
      // You need to climb up the DOM tree three levels and then to second child and then the first child is the send button
      box.parentElement.parentElement.parentElement.children[1].children[0].click();
    }
```

![Screenshot 2022-08-25 104911](https://user-images.githubusercontent.com/83443068/186645582-11796101-e533-4615-987d-3e6ffdf8f465.jpg)

This runs well and selects the send button and clicks it( typed a random input while executing and it sends) but it doesnt send the text we enter or the number of times to the chat.
Thanks

**Comment by amalsebastian7** [comment] 2022-08-25 10:52
I think it could be the issue with the loop

**Comment by PhoenixCreation** [comment] 2022-08-29 10:54
Hi @amalsebastian7, Thanks for pointing this out.  Although I was not able to reproduce this so I will need some more info from your side.
Can you provide the following information? 
- Browser Name
- Browser version
- which chat were you using?(group/personal)?
- whatsapp version

Thank you

**Comment by ghost** [comment] 2022-09-13 18:10
i have the same problem, 
i'm using Chrome (version 105.0.5195.102) with a personal chat 
whass version (0.4.930)

**Comment by PhoenixCreation** [comment] 2023-01-21 11:18
Hi, I am sorry for late response but I have been busy in other projects.

I checked with the latest version of whatsapp web and I found that they have changed the implementation from their end. So this script will not work in there.

Technical details:
- I don't remember if they were using react using or not back in the days  built this script. But they are using it now.
- Whatsapp web changed their code to start using the react hot keys and authentic event filtering.
- This allows it to block almost all scripts running from the console.
- So it is very tricky to get it work through console.

Workarounds:
- There are none to use directly from the developer console.
- You can use automation tools such as selenium with python or java to automate this process. [Not recommended, As it has higher chances of getting caught by whatsapp]

# I am leaving this issue open for other coming to this repo.

**Comment by PhoenixCreation** [comment] 2023-06-03 07:18
Hi @amalsebastian7, Sorry for late response. I have updated the script to be working again on Edge and Chrome. Although firefox is still having issues. Closing this issue as it is fixed. Feel free to reopen it if issue persists or create a new issue.

**Closed as completed by PhoenixCreation** 2023-06-03 07:18 UTC
